// Code generated by "stringer -type=PackageEcosystem -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PackageEcosystemBundler-0]
	_ = x[PackageEcosystemCargo-1]
	_ = x[PackageEcosystemComposer-2]
	_ = x[PackageEcosystemDocker-3]
	_ = x[PackageEcosystemHex-4]
	_ = x[PackageEcosystemElm-5]
	_ = x[PackageEcosystemGitSubmodule-6]
	_ = x[PackageEcosystemGitHubActions-7]
	_ = x[PackageEcosystemGoModules-8]
	_ = x[PackageEcosystemGradle-9]
	_ = x[PackageEcosystemMaven-10]
	_ = x[PackageEcosystemNpm-11]
	_ = x[PackageEcosystemNuGet-12]
	_ = x[PackageEcosystemPip-13]
	_ = x[PackageEcosystemPub-14]
	_ = x[PackageEcosystemTerraform-15]
}

const _PackageEcosystem_name = "bundlercargocomposerdockermixelmgitsubmodulegithub-actionsgomodgradlemavennpmnugetpippubterraform"

var _PackageEcosystem_index = [...]uint8{0, 7, 12, 20, 26, 29, 32, 44, 58, 63, 69, 74, 77, 82, 85, 88, 97}

func (i PackageEcosystem) String() string {
	if i >= PackageEcosystem(len(_PackageEcosystem_index)-1) {
		return "PackageEcosystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PackageEcosystem_name[_PackageEcosystem_index[i]:_PackageEcosystem_index[i+1]]
}
