builds:
  - main: .
    binary: update-dependabot
    flags:
      - -v
    goos:
      - linux
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - ppc64le
      - ppc64
      - mips64le
      - mips64
      - mipsle
      - mips
      - s390x
    goarm:
      - 5
      - 6
      - 7
    goamd64:
      - v1
      - v2
      - v3
      - v4
    gomips:
      - hardfloat
      - softfloat
